### ISSUE TITLE
RethinkDB issues

### ISSUE THREAD

**Issue by mrayva** [datamountaineer/stream-reactor#51]
1) Not sure why 'eee' in \stream-reactor\kafka-connect-rethink\src\main\scala\com\datamountaineeer\  :)
2) AUTOCREATE does not work with tasks.max > 1 -  concurrent  table creation is failing on rethinkdb
3) Primary Key is not created despite  correct log entry 
Setting primary as first field found: __PKEY__ (com.datamountaineeer.streamreactor.connect.rethink.sink.ReThinkSinkConverter$:63)
4) Need a way to ignore 'binary' fields (with settings?)  which is legal type in AVRO - otherwise stream-reactor throwing exception and terminating

**Comment by andrewstevenson** [comment]
Thanks for the feedback. I'll get on it.

**Comment by andrewstevenson** [comment]
fixed.

**Comment by mrayva** [comment]
Thanks,  

0) Creating table correctly -sans PK ( with tasks > 1 ) - but stopped writing anything/correctly either ( am I doing something wrong??? )
Rethinkdb records look like the following( even when pre-creating  table 'manually' ): 
{
"empty": false ,
"id":  "5cdd0082-2c8c-4f72-8f0b-982941021cf5"
}

From Connector's Log:

INFO Received 9 records. (com.datamountaineer.streamreactor.connect.rethink.sink.ReThinkWriter:65)
INFO Handling records for vTABLE(com.datamountaineer.streamreactor.connect.rethink.sink.ReThinkWriter:79)
INFO Wrote 9 to rethink. (com.datamountaineer.streamreactor.connect.rethink.sink.ReThinkWriter:98)

1) 'primary key' issue still not fixed

( Note __PKEY__ is not the first field - but correct 'key' in Kafka, I think )

From Logs:

[2016-09-08 20:58:58,331] INFO Creating table vTEST (com.datamountaineer.streamreactor.connect.rethink.sink.ReThinkSinkConverter$:60)
[2016-09-08 20:58:58,332] INFO Setting primary as first field found: __PKEY__ (com.datamountaineer.streamreactor.connect.rethink.sink.ReThinkSinkConverter$:66)
[2016-09-08 20:58:58,676] ERROR Failed to create table vTEST. Error message java.util.HashMap cannot be cast to scala.runtime.Nothing$ (com.datamountaineer.streamreactor.connect.rethink.sink.ReThinkSinkConverter$:71)
[2016-09-08 20:58:58,677] INFO Table vTEST created. (com.datamountaineer.streamreactor.connect.rethink.sink.ReThinkSinkConverter$:74)

Running RethinkDB r.table('vTABLE').info()
{
"db": {
"id":  "7470a94e-f3d2-4146-a90b-ee4edf51cfe2" ,
"name":  "test" ,
"type":  "DB"
} ,
"doc_count_estimates": [
0
] ,
"id":  "31f05603-c993-4181-8c59-6975f60846a7" ,
"indexes": [ ],
"name":  "vTABLE" ,
"primary_key":  "id" ,
"type":  "TABLE"
}

2) Not sure why the build  now requires easymock-3.4.jar ..?

3) 'Binary' issue is not fixed but  I've found a workaround - using KCQL 's IGNORE <binary field>

**Comment by andrewstevenson** [comment]
I'll check the pk issue again. For the binary it should be ignoring any field of type bytes from Connect.
________________________________

**Comment by andrewstevenson** [comment]
@mrayva can you check now?

**Comment by mrayva** [comment]
Looks good ( thanks! ) - except for the 'binary issue' - still appears to be failing to convert when encountering - with interesting 'twist':
Legit  MS SQL numeric(10,0), ingested into Kafka as 
{
      "name": "RECORD_ID",
      "type": {
        "type": "bytes",
        "connect.version": 1,
        "connect.parameters": {
          "scale": "0"
        },
        "connect.name": "org.apache.kafka.connect.data.Decimal"
      }

-  discarded by rethinkdb sink with 

WARN Discarding binary field RECORD_ID (com.datamountaineer.streamreactor.connect.rethink.sink.ReThinkSinkConverter$:137) 

2)  Somewhat unrelated :
trying stream-reactor
java -Dconfig.file=application.conf -jar kafka-socket-streamer-0.2-3.0.0-all.jar
and getting
"no main manifest attribute, in kafka-socket-streamer-0.2-3.0.0-all.jar" 
?

**Comment by andrewstevenson** [comment]
On the sink side Connect only exposes that the type is bytes. I've added a cast to string for any bytes type. I'll check with Confluent if they can annotate with the correct type.

Socket Streamer should be fine now aswell. 

You can join our slack channel if you prefer to communicate that way.

**Comment by stheppi** [comment]
@andrewstevenson they (confluent) set extra properties on the schema to mark it as decimal, date, time, timestamp. I have pushed the change. if the bytes it's actually a decimal will create a bigdecimal now. Furthermore if the schema point to a Date, Time,Timestamp one it would return a java.util.Date now.
Can you please release to maven?

@mrayva: once the binaries are available you can use them.

**Comment by mrayva** [comment]
what is your slack channel ( see no reference on your website)?

**Comment by stheppi** [comment]
@mrayva: Please send your email to Andrew to send you the slack invitation

**Comment by stheppi** [comment]
Please use www.datamountaineer.com to do so.

**Comment by andrewstevenson** [comment]
or andrew@datamountaineer.com
