### ISSUE TITLE
Authorization password in Redis connect is not optional

### ISSUE THREAD

**Issue by ErdtR** [datamountaineer/stream-reactor#60]
Documentation says that connect.redis.connection.password should be optional. But without this property connector doesn't work. I am always getting "Missing required configuration "connect.redis.connection.password" which has no default value" error.

**Comment by andrewstevenson** [comment]
Not quite optional but we updated the docs recently, we actually mean don't include the line at all.

_Description: If you don’t have a password set up on the redis server don’t provide the value or you will see this error: “ERR Client sent AUTH, but no password is set”_

**Comment by andrewstevenson** [comment]
we have a slack channel if you'd like to join?

**Comment by ErdtR** [comment]
There is example. It is my file with properties: 

name=redis-sink
connect.redis.connection.host=localhost
connect.redis.connection.port=6379
connector.class=com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkConnector
tasks.max=1
topics=drones_path
connect.redis.export.route.query=INSERT INTO TABLE1 SELECT * FROM drones_path

I don't include the line. But I am still getting "Missing required configuration "connect.redis.connection.password" which has no default value" error when I try to run connector. So I think it is a problem in code, isn't it?

Thank you, but I wouldn't join your slack channel yet.

**Comment by stheppi** [comment]
@ErdtR I just pushed the fix; if you don't provide the password the error won't be thrown. You can build using the latest. We will release a new version soon.

**Comment by renou** [comment]
+1, any plan on releasing?

**Comment by andrewstevenson** [comment]
I'm preparing a release for this weekend.

**Comment by renou** [comment]
Awesome, thank you!
